### ISSUE TITLE
Streamline startpage and system requirements detail

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3/get.typo3.org#427] opened 2023-12-12 09:46 UTC
The startpage https://get.typo3.org/ lists PHP 8.1 and PHP 8.2 for TYPO3 v12.
The detail page also lists PHP 8.3: https://get.typo3.org/version/12#system-requirements

I guess this should be streamlined.

**Comment by ohader** [comment] 2024-01-26 16:34
Sounds like a duplicate of #428 - however, it is fixed and deployed now 👍

**Closed as completed by ohader** 2024-01-26 16:34 UTC
